### PR TITLE
Config templates.  In-Place Install.  Tar cookbook.  Code coverage.

### PR DESCRIPTION
**Pull request by mdbelt**
@fgimenez - Could I get your thoughts on this?  I'm eager to hear your feedback.  Does this deserve a new version num?

Here is what I've done:
*  Added additional attributes for hazelcast configuration of OrientDB
*  Expanded README to account for new attributes & put into table view with defaults.
*  Alter the OrientDB init_script for correct return value on status command so Chef correctly interprets service status & make stop a modal command.
*  Switched to using ERB templates for generating configuration files with values from Chef (above).
*  Switched to an in-place install (overlay) instead of blast-and-fill.
*  Switched to using TAR cookbook to manage download (allows for Chef cache use & setting group, user, & mode on extract)
*  Expanded specs to account for new resources.
*  Expanded specs to get 100% code coverage.

### CODE REVIEW

**Comment by fgimenez** [comment]
@mdbelt this is great, thanks a lot for your work! It's a huge improvement for the cookbook.

Only a minor issue, shouldn't the orientdb-client-log.properties.erb and orientdb-server-log.properties.erb templates be cookbook_files instead? There's no interpolation in them.

I'm putting in place a base test kitchen harness for having also integration test for the cookbook, this with your pr will make a good new version imo.

Cheers!

**Comment by mdbelt** [comment]
@fgimenez - I agree with both observations.

Regarding the extra config files, I had put all four as an ERB to facilitate future interpolation, but the con in doing so for the extra 2 is that is just 2 additional files to keep synchronized with OrientDB.  If I just remove the extra 2 altogether the tar file will contain the default I believe.

Regarding the duplicate test I had done so for code coverage report.  I found that since the default_spec was spinning off a runner with default values for all the recipes it was creating several default resources that errantly reported as untested.  If I set all the same values at the top of default_spec that are in the other specs it will clear this.  I had just chosen to test the default as well.

On Monday I'll remove the extra 2 config files as well as remove the default tests & set the custom values to be consistent in the default_spec as with the rest of the specs.

**Comment by mdbelt** [comment]
@fgimenez - Additional changes made.
*  Removed properties files from templates
*  Consolidated custom variables into the spec_helper & referenced from each spec & default_spec to allow for proper code coverage report.

Note:  I know you like the commits squashed, but I can't figure out how to get it to do so with a merge of your code from the upstream in the middle.

**Comment by fgimenez** [comment]
Ok thanks a lot, I think that there was no need to rebase your changes, anyway already merged :)

**Pull request merged**
